services:
  postgres:
    image: "pgvector/pgvector:pg17"
    container_name: knowflow-postgres
    environment:
      - "POSTGRES_DB=knowflow"
      - "POSTGRES_PASSWORD=knowflow"
      - "POSTGRES_USER=knowflow"
    ports:
      - "5432:5432"
    volumes:
      - knowflow-postgres-data:/var/lib/postgresql/data

volumes:
  knowflow-postgres-data:
